#pragma once
#include "utils.h"
//Due to my goofy-ass 1-cpp-dozen-header project structure, this will work quite well actually.
int max_enemy_bullets=20;
//big array because thou shalt not use malloc/free/new/delete.
float enemy_projectiles[]={
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
    BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,BULLET_INVALID,
};
float shipXE=50.0,shipYE=80.0;
float shipRotXE=1.0,shipRotYE=0.0;
//float camXE=0.0,camYE=0.0;
//float TrueCamXE=0.0;
float shipVelXE=0.0,shipVelYE=0.0;
int player_shot_cooldownE=0;
int iFramesE=20;
int heartsE=20;
float invalid_timeE=0.0f;
